StringValues="IconImagePhotometricInterpretation" {
	MONOCHROME1,
	MONOCHROME2,
	PALETTE COLOR
}

StringValues="DirectoryRecordType" {
	PATIENT,
	STUDY,
	SERIES,
	IMAGE,
	RADIOTHERAPY,
	RT DOSE,
	RT STRUCTURE SET,
	RT PLAN,
	RT TREAT RECORD,
	PRESENTATION,
	SR DOCUMENT,
	KEY OBJECT DOC,
	WAVEFORM,
	SPECTROSCOPY,
	RAW DATA,
	REGISTRATION,
	FIDUCIAL,
	HANGING PROTOCOL,
	ENCAP DOC,
	HL7 STRUC DOC,
	STEREOMETRIC,
	VALUE MAP,
	PALETTE,
	IMPLANT,
	IMPLANT GROUP,
	IMPLANT ASSY,
	MEASUREMENT,
	SURFACE,
	PRIVATE
}

StringValues="DentalMediaProfileSOPClasses" {
	1.2.840.10008.5.1.4.1.1.1.3,
	1.2.840.10008.5.1.4.1.1.1.1
}

StringValues="DentalMediaProfileTransferSyntaxes" {
	1.2.840.10008.1.2.1
}

