(0014,0023) VERS="DICONDE"	VR="ST"   VM="1"	Keyword="CADFileFormat"										Name="CAD File Format (Retired)"
(0014,0024) VERS="DICONDE"	VR="ST"   VM="1"	Keyword="ComponentReferenceSystem"							Name="Component Reference System (Retired)"
(0014,0025) VERS="DICONDE"	VR="ST"   VM="1"	Keyword="ComponentManufacturingProcedure"					Name="Component Manufacturing Procedure"
(0014,0028) VERS="DICONDE"	VR="ST"   VM="1"	Keyword="ComponentManufacturer"								Name="Component Manufacturer"
(0014,0030) VERS="DICONDE"	VR="DS"   VM="1-n"	Keyword="MaterialThickness"									Name="Material Thickness"
(0014,0032) VERS="DICONDE"	VR="DS"   VM="1-n"	Keyword="MaterialPipeDiameter"								Name="Material Pipe Diameter"
(0014,0034) VERS="DICONDE"	VR="DS"   VM="1-n"	Keyword="MaterialIsolationDiameter"							Name="Material Isolation Diameter"
(0014,0042) VERS="DICONDE"	VR="ST"   VM="1"	Keyword="MaterialGrade"										Name="Material Grade"
(0014,0044) VERS="DICONDE"	VR="ST"   VM="1"	Keyword="MaterialPropertiesDescription"						Name="Material Properties Description"
(0014,0045) VERS="DICONDE"	VR="ST"   VM="1"	Keyword="MaterialPropertiesFileFormatRetired"				Name="Material Properties File Format (Retired)"
(0014,0046) VERS="DICONDE"	VR="LT"   VM="1"	Keyword="MaterialNotes"										Name="Material Notes"
(0014,0050) VERS="DICONDE"	VR="CS"   VM="1"	Keyword="ComponentShape"									Name="Component Shape"
(0014,0052) VERS="DICONDE"	VR="CS"   VM="1"	Keyword="CurvatureType"										Name="Curvature Type"
(0014,0054) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="OuterDiameter"										Name="Outer Diameter"
(0014,0056) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="InnerDiameter"										Name="Inner Diameter"
(0014,0100) VERS="DICONDE"	VR="LO"   VM="1-n"	Keyword="ComponentWelderIDs"								Name="Component Welder IDs"
(0014,0101) VERS="DICONDE"	VR="CS"   VM="1"	Keyword="SecondaryApprovalStatus"							Name="Secondary Approval Status"
(0014,0102) VERS="DICONDE"	VR="DA"   VM="1"	Keyword="SecondaryReviewDate"								Name="Secondary Review Date"
(0014,0103) VERS="DICONDE"	VR="TM"   VM="1"	Keyword="SecondaryReviewTime"								Name="Secondary Review Time"
(0014,0104) VERS="DICONDE"	VR="PN"   VM="1"	Keyword="SecondaryReviewerName"								Name="Secondary Reviewer Name"
(0014,0105) VERS="DICONDE"	VR="ST"   VM="1"	Keyword="RepairID"											Name="Repair ID"
(0014,0106) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="MultipleComponentApprovalSequence"					Name="Multiple Component Approval Sequence"
(0014,0107) VERS="DICONDE"	VR="CS"   VM="1-n"	Keyword="OtherApprovalStatus"								Name="Other Approval Status"
(0014,0108) VERS="DICONDE"	VR="CS"   VM="1-n"	Keyword="OtherSecondaryApprovalStatus"						Name="Other Secondary Approval Status"
(0014,0200) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="DataElementLabelSequence"							Name="Data Element Label Sequence"
(0014,0201) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="DataElementLabelItemSequence"						Name="Data Element Label Item Sequence"
(0014,0202) VERS="DICONDE"	VR="AT"   VM="1"	Keyword="DataElement"										Name="Data Element"
(0014,0203) VERS="DICONDE"	VR="LO"   VM="1"	Keyword="DataElementName"									Name="Data Element Name"
(0014,0204) VERS="DICONDE"	VR="LO"   VM="1"	Keyword="DataElementDescription"							Name="Data Element Description"
(0014,0205) VERS="DICONDE"	VR="CS"   VM="1"	Keyword="DataElementConditionality"							Name="Data Element Conditionality"
(0014,0206) VERS="DICONDE"	VR="IS"   VM="1"	Keyword="DataElementMinimumCharacters"						Name="Data Element Minimum Characters"
(0014,0207) VERS="DICONDE"	VR="IS"   VM="1"	Keyword="DataElementMaximumCharacters"						Name="Data Element Maximum Characters"
(0014,1010) VERS="DICONDE"	VR="ST"   VM="1"	Keyword="ActualEnvironmentalConditions"						Name="Actual Environmental Conditions"
(0014,1020) VERS="DICONDE"	VR="DA"   VM="1"	Keyword="ExpiryDate"										Name="Expiry Date"
(0014,1040) VERS="DICONDE"	VR="ST"   VM="1"	Keyword="EnvironmentalConditions"							Name="Environmental Conditions"
(0014,2002) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="EvaluatorSequence"									Name="Evaluator Sequence"
(0014,2004) VERS="DICONDE"	VR="IS"   VM="1"	Keyword="EvaluatorNumber"									Name="Evaluator Number"
(0014,2006) VERS="DICONDE"	VR="PN"   VM="1"	Keyword="EvaluatorName"										Name="Evaluator Name"
(0014,2008) VERS="DICONDE"	VR="IS"   VM="1"	Keyword="EvaluationAttempt"									Name="Evaluation Attempt"
(0014,2012) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="IndicationSequence"								Name="Indication Sequence"
(0014,2014) VERS="DICONDE"	VR="IS"   VM="1"	Keyword="IndicationNumber"									Name="Indication Number "
(0014,2016) VERS="DICONDE"	VR="SH"   VM="1"	Keyword="IndicationLabel"									Name="Indication Label"
(0014,2018) VERS="DICONDE"	VR="ST"   VM="1"	Keyword="IndicationDescription"								Name="Indication Description"
(0014,201A) VERS="DICONDE"	VR="CS"   VM="1-n"	Keyword="IndicationType"									Name="Indication Type"
(0014,201C) VERS="DICONDE"	VR="CS"   VM="1"	Keyword="IndicationDisposition"								Name="Indication Disposition"
(0014,201E) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="IndicationROISequence"								Name="Indication ROI Sequence"
(0014,2030) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="IndicationPhysicalPropertySequence"				Name="Indication Physical Property Sequence"
(0014,2032) VERS="DICONDE"	VR="SH"   VM="1"	Keyword="PropertyLabel"										Name="Property Label"
(0014,2202) VERS="DICONDE"	VR="IS"   VM="1"	Keyword="CoordinateSystemNumberOfAxes"						Name="Coordinate System Number of Axes "
(0014,2204) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="CoordinateSystemAxesSequence"						Name="Coordinate System Axes Sequence"
(0014,2206) VERS="DICONDE"	VR="ST"   VM="1"	Keyword="CoordinateSystemAxisDescription"					Name="Coordinate System Axis Description"
(0014,2208) VERS="DICONDE"	VR="CS"   VM="1"	Keyword="CoordinateSystemDataSetMapping"					Name="Coordinate System Data Set Mapping"
(0014,220A) VERS="DICONDE"	VR="IS"   VM="1"	Keyword="CoordinateSystemAxisNumber"						Name="Coordinate System Axis Number"
(0014,220C) VERS="DICONDE"	VR="CS"   VM="1"	Keyword="CoordinateSystemAxisType"							Name="Coordinate System Axis Type"
(0014,220E) VERS="DICONDE"	VR="CS"   VM="1"	Keyword="CoordinateSystemAxisUnits"							Name="Coordinate System Axis Units"
(0014,2210) VERS="DICONDE"	VR="OB"   VM="1"	Keyword="CoordinateSystemAxisValues"						Name="Coordinate System Axis Values"
(0014,2220) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="CoordinateSystemTransformSequence"					Name="Coordinate System Transform Sequence"
(0014,2222) VERS="DICONDE"	VR="ST"   VM="1"	Keyword="TransformDescription"								Name="Transform Description"
(0014,2224) VERS="DICONDE"	VR="IS"   VM="1"	Keyword="TransformNumberOfAxes"								Name="Transform Number of Axes"
(0014,2226) VERS="DICONDE"	VR="IS"   VM="1-n"	Keyword="TransformOrderOfAxes"								Name="Transform Order of Axes"
(0014,2228) VERS="DICONDE"	VR="CS"   VM="1"	Keyword="TransformedAxisUnits"								Name="Transformed Axis Units"
(0014,222A) VERS="DICONDE"	VR="DS"   VM="1-n"	Keyword="CoordinateSystemTransformRotationAndScaleMatrix"	Name="Coordinate System Transform Rotation and Scale Matrix"
(0014,222C) VERS="DICONDE"	VR="DS"   VM="1-n"	Keyword="CoordinateSystemTransformTranslationMatrix"		Name="Coordinate System Transform Translation Matrix"
(0014,3011) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="InternalDetectorFrameTime"							Name="Internal Detector Frame Time"
(0014,3012) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="NumberOfFramesIntegrated"							Name="Number of Frames Integrated"
(0014,3020) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="DetectorTemperatureSequence"						Name="Detector Temperature Sequence"
(0014,3022) VERS="DICONDE"	VR="ST"   VM="1"	Keyword="SensorName"										Name="Sensor Name"
(0014,3024) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="HorizontalOffsetOfSensor"							Name="Horizontal Offset of Sensor"
(0014,3026) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="VerticalOffsetOfSensor"							Name="Vertical Offset of Sensor"
(0014,3028) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="SensorTemperature"									Name="Sensor Temperature"
(0014,3040) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="DarkCurrentSequence"								Name="Dark Current Sequence"
(0014,3050) VERS="DICONDE"	VR="OW/OB" VM="1"	Keyword="DarkCurrentCounts"									Name="Dark Current Counts"
(0014,3060) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="GainCorrectionReferenceSequence"					Name="Gain Correction Reference Sequence"
(0014,3070) VERS="DICONDE"	VR="OW/OB" VM="1"	Keyword="AirCounts"											Name="Air Counts"
(0014,3071) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="KVUsedInGainCalibration"							Name="KV Used in Gain Calibration"
(0014,3072) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="MAUsedInGainCalibration"							Name="MA Used in Gain Calibration"
(0014,3073) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="NumberOfFramesUsedForIntegration"					Name="Number of Frames Used for Integration"
(0014,3074) VERS="DICONDE"	VR="LO"   VM="1"	Keyword="FilterMaterialUsedInGainCalibration"				Name="Filter Material Used in Gain Calibration"
(0014,3075) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="FilterThicknessUsedInGainCalibration"				Name="Filter Thickness Used in Gain Calibration"
(0014,3076) VERS="DICONDE"	VR="DA"   VM="1"	Keyword="DateOfGainCalibration"								Name="Date of Gain Calibration"
(0014,3077) VERS="DICONDE"	VR="TM"   VM="1"	Keyword="TimeOfGainCalibration"								Name="Time of Gain Calibration"
(0014,3080) VERS="DICONDE"	VR="OB"   VM="1"	Keyword="BadPixelImage"										Name="Bad Pixel Image"
(0014,3099) VERS="DICONDE"	VR="LT"   VM="1"	Keyword="CalibrationNotes"									Name="Calibration Notes"
(0014,3100) VERS="DICONDE"	VR="LT"   VM="1"	Keyword="LinearityCorrectionTechnique"						Name="Linearity Correction Technique"
(0014,3101) VERS="DICONDE"	VR="LT"   VM="1"	Keyword="BeamHardeningCorrectionTechnique"					Name="Beam Hardening Correction Technique"
(0014,4002) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="PulserEquipmentSequence"							Name="Pulser Equipment Sequence"
(0014,4004) VERS="DICONDE"	VR="CS"   VM="1"	Keyword="PulserType"										Name="Pulser Type"
(0014,4006) VERS="DICONDE"	VR="LT"   VM="1"	Keyword="PulserNotes"										Name="Pulser Notes"
(0014,4008) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="ReceiverEquipmentSequence"							Name="Receiver Equipment Sequence"
(0014,400A) VERS="DICONDE"	VR="CS"   VM="1"	Keyword="AmplifierType"										Name="Amplifier Type"
(0014,400C) VERS="DICONDE"	VR="LT"   VM="1"	Keyword="ReceiverNotes"										Name="Receiver Notes"
(0014,400E) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="PreAmplifierEquipmentSequence"						Name="Pre-Amplifier Equipment Sequence"
(0014,400F) VERS="DICONDE"	VR="LT"   VM="1"	Keyword="PreAmplifierNotes"									Name="Pre-Amplifier Notes"
(0014,4010) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="TransmitTransducerSequence"						Name="Transmit Transducer Sequence"
(0014,4011) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="ReceiveTransducerSequence"							Name="Receive Transducer Sequence"
(0014,4012) VERS="DICONDE"	VR="US"   VM="1"	Keyword="NumberOfElements"									Name="Number of Elements"
(0014,4013) VERS="DICONDE"	VR="CS"   VM="1"	Keyword="ElementShape"										Name="Element Shape"
(0014,4014) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="ElementDimensionA"									Name="Element Dimension A"
(0014,4015) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="ElementDimensionB"									Name="Element Dimension B"
(0014,4016) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="ElementPitchA"										Name="Element Pitch A"
(0014,4017) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="MeasuredBeamDimensionA"							Name="Measured Beam Dimension A"
(0014,4018) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="MeasuredBeamDimensionB"							Name="Measured Beam Dimension B"
(0014,4019) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="LocationOfMeasuredBeamDiameter"					Name="Location of Measured Beam Diameter"
(0014,401A) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="NominalFrequency"									Name="Nominal Frequency"
(0014,401B) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="MeasuredCenterFrequency"							Name="Measured Center Frequency"
(0014,401C) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="MeasuredBandwidth"									Name="Measured Bandwidth"
(0014,401D) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="ElementPitchB"										Name="Element Pitch B"
(0014,4020) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="PulserSettingsSequence"							Name="Pulser Settings Sequence"
(0014,4022) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="PulseWidth"										Name="Pulse Width"
(0014,4024) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="ExcitationFrequency"								Name="Excitation Frequency"
(0014,4026) VERS="DICONDE"	VR="CS"   VM="1"	Keyword="ModulationType"									Name="Modulation Type"
(0014,4028) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="Damping"											Name="Damping"
(0014,4030) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="ReceiverSettingsSequence"							Name="Receiver Settings Sequence"
(0014,4031) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="AcquiredSoundpathLength"							Name="Acquired Soundpath Length"
(0014,4032) VERS="DICONDE"	VR="CS"   VM="1"	Keyword="AcquisitionCompressionType"						Name="Acquisition Compression Type"
(0014,4033) VERS="DICONDE"	VR="IS"   VM="1"	Keyword="AcquisitionSampleSize"								Name="Acquisition Sample Size"
(0014,4034) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="RectifierSmoothing"								Name="Rectifier Smoothing"
(0014,4035) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="DACSequence"										Name="DAC Sequence"
(0014,4036) VERS="DICONDE"	VR="CS"   VM="1"	Keyword="DACType"											Name="DAC Type"
(0014,4038) VERS="DICONDE"	VR="DS"   VM="1-n"	Keyword="DACGainPoints"										Name="DAC Gain Points"
(0014,403A) VERS="DICONDE"	VR="DS"   VM="1-n"	Keyword="DACTimePoints"										Name="DAC Time Points"
(0014,403C) VERS="DICONDE"	VR="DS"   VM="1-n"	Keyword="DACAmplitude"										Name="DAC Amplitude"
(0014,4040) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="PreAmplifierSettingsSequence"						Name="Pre-Amplifier Settings Sequence"
(0014,4050) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="TransmitTransducerSettingsSequence"				Name="Transmit Transducer Settings Sequence"
(0014,4051) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="ReceiveTransducerSettingsSequence"					Name="Receive Transducer Settings Sequence"
(0014,4052) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="IncidentAngle"										Name="Incident Angle"
(0014,4054) VERS="DICONDE"	VR="ST"   VM="1"	Keyword="CouplingTechnique"									Name="Coupling Technique"
(0014,4056) VERS="DICONDE"	VR="ST"   VM="1"	Keyword="CouplingMedium"									Name="Coupling Medium"
(0014,4057) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="CouplingVelocity"									Name="Coupling Velocity"
(0014,4058) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="ProbeCenterLocationX"								Name="Probe Center Location X"
(0014,4059) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="ProbeCenterLocationZ"								Name="Probe Center Location Z"
(0014,405A) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="SoundPathLength"									Name="Sound Path Length"
(0014,405C) VERS="DICONDE"	VR="ST"   VM="1"	Keyword="DelayLawIdentifier"								Name="Delay Law Identifier"
(0014,4060) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="GateSettingsSequence"								Name="Gate Settings Sequence"
(0014,4062) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="GateThreshold"										Name="Gate Threshold"
(0014,4064) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="VelocityOfSound"									Name="Velocity of Sound"
(0014,4070) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="CalibrationSettingsSequence"						Name="Calibration Settings Sequence"
(0014,4072) VERS="DICONDE"	VR="ST"   VM="1"	Keyword="CalibrationProcedure"								Name="Calibration Procedure"
(0014,4074) VERS="DICONDE"	VR="SH"   VM="1"	Keyword="ProcedureVersion"									Name="Procedure Version"
(0014,4076) VERS="DICONDE"	VR="DA"   VM="1"	Keyword="ProcedureCreationDate"								Name="Procedure Creation Date"
(0014,4078) VERS="DICONDE"	VR="DA"   VM="1"	Keyword="ProcedureExpirationDate"							Name="Procedure Expiration Date"
(0014,407A) VERS="DICONDE"	VR="DA"   VM="1"	Keyword="ProcedureLastModifiedDate"							Name="Procedure Last Modified Date"
(0014,407C) VERS="DICONDE"	VR="TM"   VM="1-n"	Keyword="CalibrationTime"									Name="Calibration Time"
(0014,407E) VERS="DICONDE"	VR="DA"   VM="1-n"	Keyword="CalibrationDate"									Name="Calibration Date"
(0014,4080) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="ProbeDriveEquipmentSequence"						Name="Probe Drive Equipment Sequence"
(0014,4081) VERS="DICONDE"	VR="CS"   VM="1"	Keyword="DriveType"											Name="Drive Type"
(0014,4082) VERS="DICONDE"	VR="LT"   VM="1"	Keyword="ProbeDriveNotes"									Name="Probe Drive Notes"
(0014,4083) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="DriveProbeSequence"								Name="Drive Probe Sequence"
(0014,4084) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="ProbeInductance"									Name="Probe Inductance"
(0014,4085) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="ProbeResistance"									Name="Probe Resistance"
(0014,4086) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="ReceiveProbeSequence"								Name="Receive Probe Sequence"
(0014,4087) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="ProbeDriveSettingsSequence"						Name="Probe Drive Settings Sequence"
(0014,4088) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="BridgeResistors"									Name="Bridge Resistors"
(0014,4089) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="ProbeOrientationAngle"								Name="Probe Orientation Angle"
(0014,408B) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="UserSelectedGainY"									Name="User Selected Gain Y"
(0014,408C) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="UserSelectedPhase"									Name="User Selected Phase"
(0014,408D) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="UserSelectedOffsetX"								Name="User Selected Offset X"
(0014,408E) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="UserSelectedOffsetY"								Name="User Selected Offset Y"
(0014,4091) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="ChannelSettingsSequence"							Name="Channel Settings Sequence"
(0014,4092) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="ChannelThreshold"									Name="Channel Threshold"
(0014,409A) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="ScannerSettingsSequence"							Name="Scanner Settings Sequence"
(0014,409B) VERS="DICONDE"	VR="ST"   VM="1"	Keyword="ScanProcedure"										Name="Scan Procedure"
(0014,409C) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="TranslationRateX"									Name="Translation Rate X"
(0014,409D) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="TranslationRateY"									Name="Translation Rate Y"
(0014,409F) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="ChannelOverlap"									Name="Channel Overlap"
(0014,40A0) VERS="DICONDE"	VR="LO"   VM="1"	Keyword="ImageQualityIndicatorType"							Name="Image Quality Indicator Type"
(0014,40A1) VERS="DICONDE"	VR="LO"   VM="1"	Keyword="ImageQualityIndicatorMaterial"						Name="Image Quality Indicator Material"
(0014,40A2) VERS="DICONDE"	VR="LO"   VM="1"	Keyword="ImageQualityIndicatorSize"							Name="Image Quality Indicator Size"
(0014,5002) VERS="DICONDE"	VR="IS"   VM="1"	Keyword="LINACEnergy"										Name="LINAC Energy"
(0014,5004) VERS="DICONDE"	VR="IS"   VM="1"	Keyword="LINACOutput"										Name="LINAC Output"
(0014,5100) VERS="DICONDE"	VR="US"   VM="1"	Keyword="ActiveAperture"									Name="Active Aperture"
(0014,5101) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="TotalAperture"										Name="Total Aperture"
(0014,5102) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="ApertureElevation"									Name="Aperture Elevation"
(0014,5103) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="MainLobeAngle"										Name="Main Lobe Angle"
(0014,5104) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="MainRoofAngle"										Name="Main Roof Angle"
(0014,5105) VERS="DICONDE"	VR="CS"   VM="1"	Keyword="ConnectorType"										Name="Connector Type"
(0014,5106) VERS="DICONDE"	VR="SH"   VM="1"	Keyword="WedgeModelNumber"									Name="Wedge Model Number"
(0014,5107) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="WedgeAngleFloat"									Name="Wedge Angle Float"
(0014,5108) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="WedgeRoofAngle"									Name="Wedge Roof Angle"
(0014,5109) VERS="DICONDE"	VR="CS"   VM="1"	Keyword="WedgeElement1Position"								Name="Wedge Element 1 Position"
(0014,510A) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="WedgeMaterialVelocity"								Name="Wedge Material Velocity"
(0014,510B) VERS="DICONDE"	VR="SH"   VM="1"	Keyword="WedgeMaterial"										Name="Wedge Material"
(0014,510C) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="WedgeOffsetZ"										Name="Wedge Offset Z"
(0014,510D) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="WedgeOriginOffsetX"								Name="Wedge Origin Offset X"
(0014,510E) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="WedgeTimeDelay"									Name="Wedge Time Delay"
(0014,510F) VERS="DICONDE"	VR="SH"   VM="1"	Keyword="WedgeName"											Name="Wedge Name"
(0014,5110) VERS="DICONDE"	VR="SH"   VM="1"	Keyword="WedgeManufacturerName"								Name="Wedge Manufacturer Name"
(0014,5111) VERS="DICONDE"	VR="LO"   VM="1"	Keyword="WedgeDescription"									Name="Wedge Description"
(0014,5112) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="NominalBeamAngle"									Name="Nominal Beam Angle"
(0014,5113) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="WedgeOffsetX"										Name="Wedge Offset X"
(0014,5114) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="WedgeOffsetY"										Name="Wedge Offset Y"
(0014,5115) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="WedgeTotalLength"									Name="Wedge Total Length"
(0014,5116) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="WedgeInContactLength"								Name="Wedge In Contact Length"
(0014,5117) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="WedgeFrontGap"										Name="Wedge Front Gap"
(0014,5118) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="WedgeTotalHeight"									Name="Wedge Total Height"
(0014,5119) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="WedgeFrontHeight"									Name="Wedge Front Height"
(0014,511A) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="WedgeRearHeight"									Name="Wedge Rear Height"
(0014,511B) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="WedgeTotalWidth"									Name="Wedge Total Width"
(0014,511C) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="WedgeInContactWidth"								Name="Wedge In Contact Width"
(0014,511D) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="WedgeChamferHeight"								Name="Wedge Chamfer Height"
(0014,511E) VERS="DICONDE"	VR="CS"   VM="1"	Keyword="WedgeCurve"										Name="Wedge Curve"
(0014,511F) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="RadiusAlongWedge"									Name="Radius Along the Wedge"
(0014,6001) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="ThermalCameraSettingsSequence"						Name="Thermal Camera Settings Sequence"
(0014,6002) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="AcquisitionFrameRate"								Name="Acquisition Frame Rate"
(0014,6003) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="IntegrationTime"									Name="Integration Time"
(0014,6004) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="NumberOfCalibrationFrames"							Name="Number of Calibration Frames"
(0014,6005) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="NumberOfRowsInFullAcquisitionImage"				Name="Number of Rows in Full Acquisition Image"
(0014,6006) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="NumberOfColumnsInFullAcquisitionImage"				Name="Number Of Columns in Full Acquisition Image"
(0014,6007) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="ThermalSourceSettingsSequence"						Name="Thermal Source Settings Sequence"
(0014,6008) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="SourceHorizontalPitch"								Name="Source Horizontal Pitch"
(0014,6009) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="SourceVerticalPitch"								Name="Source Vertical Pitch"
(0014,600A) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="SourceHorizontalScanSpeed"							Name="Source Horizontal Scan Speed"
(0014,600B) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="ThermalSourceModulationFrequency"					Name="Thermal Source Modulation Frequency"
(0014,600C) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="InductionSourceSettingSequence"					Name="Induction Source Setting Sequence"
(0014,600D) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="CoilFrequency"										Name="Coil Frequency"
(0014,600E) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="CurrentAmplitudeAcrossCoil"						Name="Current Amplitude Across Coil"
(0014,600F) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="FlashSourceSettingSequence"						Name="Flash Source Setting Sequence"
(0014,6010) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="FlashDuration"										Name="Flash Duration"
(0014,6011) VERS="DICONDE"	VR="DS"   VM="1-n"	Keyword="FlashFrameNumber"									Name="Flash Frame Number"
(0014,6012) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="LaserSourceSettingSequence"						Name="Laser Source Setting Sequence"
(0014,6013) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="HorizontalLaserSpotDimension"						Name="Horizontal Laser Spot Dimension"
(0014,6014) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="VerticalLaserSpotDimension"						Name="Vertical Laser Spot Dimension"
(0014,6015) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="LaserWavelength"									Name="Laser Wavelength"
(0014,6016) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="LaserPower"										Name="Laser Power"
(0014,6017) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="ForcedGasSettingSequence"							Name="Forced Gas Setting Sequence"
(0014,6018) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="VibrationSourceSettingSequence"					Name="Vibration Source Setting Sequence"
(0014,6019) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="VibrationExcitationFrequency"						Name="Vibration Excitation Frequency"
(0014,601A) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="VibrationExcitationVoltage"						Name="Vibration Excitation Voltage"
(0014,601B) VERS="DICONDE"	VR="CS"   VM="1"	Keyword="ThermographyDataCaptureMethod"						Name="Thermography Data Capture Method"
(0014,601C) VERS="DICONDE"	VR="CS"   VM="1"	Keyword="ThermalTechnique"									Name="Thermal Technique"
(0014,601D) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="ThermalCameraCoreSequence"							Name="Thermal Camera Core Sequence"
(0014,601E) VERS="DICONDE"	VR="CS"   VM="1"	Keyword="DetectorWavelengthRange"							Name="Detector Wavelength Range"
(0014,601F) VERS="DICONDE"	VR="CS"   VM="1"	Keyword="ThermalCameraCalibrationType"						Name="Thermal Camera Calibration Type"
(0014,6020) VERS="DICONDE"	VR="UV"   VM="1"	Keyword="AcquisitionImageCounter"							Name="Acquisition Image Counter"
(0014,6021) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="FrontPanelTemperature"								Name="Front Panel Temperature"
(0014,6022) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="AirGapTemperature"									Name="Air Gap Temperature"
(0014,6023) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="VerticalPixelSize"									Name="Vertical Pixel Size"
(0014,6024) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="HorizontalPixelSize"								Name="Horizontal Pixel Size"
(0014,6025) VERS="DICONDE"	VR="ST"   VM="1-n"	Keyword="DataStreamingProtocol"								Name="Data Streaming Protocol"
(0014,6026) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="LensSequence"										Name="Lens Sequence"
(0014,6027) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="FieldOfView"										Name="Field of View"
(0014,6028) VERS="DICONDE"	VR="LO"   VM="1"	Keyword="LensFilterManufacturer"							Name="Lens Filter Manufacturer"
(0014,6029) VERS="DICONDE"	VR="CS"   VM="1"	Keyword="CutoffFilterType"									Name="Cutoff Filter Type"
(0014,602A) VERS="DICONDE"	VR="DS"   VM="1-n"	Keyword="LensFilterCutOffWavelength"						Name="Lens Filter Cut-Off Wavelength"
(0014,602B) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="ThermalSourceSequence"								Name="Thermal Source Sequence"
(0014,602C) VERS="DICONDE"	VR="CS"   VM="1"	Keyword="ThermalSourceMotionState"							Name="Thermal Source Motion State"
(0014,602D) VERS="DICONDE"	VR="CS"   VM="1"	Keyword="ThermalSourceMotionType"							Name="Thermal Source Motion Type"
(0014,602E) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="InductionHeatingSequence"							Name="Induction Heating Sequence"
(0014,602F) VERS="DICONDE"	VR="ST"   VM="1"	Keyword="CoilConfigurationID"								Name="Coil Configuration ID"
(0014,6030) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="NumberOfTurnsInCoil"								Name="Number of Turns in Coil"
(0014,6031) VERS="DICONDE"	VR="CS"   VM="1"	Keyword="ShapeOfIndividualTurn"								Name="Shape of Individual Turn"
(0014,6032) VERS="DICONDE"	VR="DS"   VM="1-n"	Keyword="SizeOfIndividualTurn"								Name="Size of Individual Turn"
(0014,6033) VERS="DICONDE"	VR="DS"   VM="1-n"	Keyword="DistanceBetweenTurns"								Name="Distance Between Turns"
(0014,6034) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="FlashHeatingSequence"								Name="Flash Heating Sequence"
(0014,6035) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="NumberOfLamps"										Name="Number of Lamps"
(0014,6036) VERS="DICONDE"	VR="ST"   VM="1"	Keyword="FlashSynchronizationProtocol"						Name="Flash Synchronization Protocol"
(0014,6037) VERS="DICONDE"	VR="CS"   VM="1"	Keyword="FlashModificationStatus"							Name="Flash Modification Status"
(0014,6038) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="LaserHeatingSequence"								Name="Laser Heating Sequence"
(0014,6039) VERS="DICONDE"	VR="LO"   VM="1"	Keyword="LaserManufacturer"									Name="Laser Manufacturer"
(0014,603A) VERS="DICONDE"	VR="LO"   VM="1"	Keyword="LaserModelNumber"									Name="Laser Model Number"
(0014,603B) VERS="DICONDE"	VR="ST"   VM="1"	Keyword="LaserTypeDescription"								Name="Laser Type Description"
(0014,603C) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="ForcedGasHeatingSequence"							Name="Forced Gas Heating Sequence"
(0014,603D) VERS="DICONDE"	VR="LO"   VM="1"	Keyword="GasUsedForHeatingCoolingPart"						Name="Gas Used for Heating/Cooling Part"
(0014,603E) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="VibrationSonicHeatingSequence"						Name="Vibration/Sonic Heating Sequence"
(0014,603F) VERS="DICONDE"	VR="LO"   VM="1"	Keyword="ProbeManufacturer"									Name="Probe Manufacturer"
(0014,6040) VERS="DICONDE"	VR="LO"   VM="1"	Keyword="ProbeModelNumber"									Name="Probe Model Number"
(0014,6041) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="ApertureSize"										Name="Aperture Size"
(0014,6042) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="ProbeResonantFrequency"							Name="Probe Resonant Frequency"
(0014,6043) VERS="DICONDE"	VR="UT"   VM="1"	Keyword="HeatSourceDescription"								Name="Heat Source Description"
(0014,6044) VERS="DICONDE"	VR="CS"   VM="1"	Keyword="SurfacePreparationWithOpticalCoating"				Name="Surface Preparation with Optical Coating"
(0014,6045) VERS="DICONDE"	VR="ST"   VM="1"	Keyword="OpticalCoatingType"								Name="Optical Coating Type"
(0014,6046) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="ThermalConductivityOfExposedSurface"				Name="Thermal Conductivity of Exposed Surface"
(0014,6047) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="MaterialDensity"									Name="Material Density"
(0014,6048) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="SpecificHeatOfInspectionSurface"					Name="Specific Heat of Inspection Surface"
(0014,6049) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="EmissivityOfInspectionSurface"						Name="Emissivity of Inspection Surface"
(0014,604A) VERS="DICONDE"	VR="CS"   VM="1-n"	Keyword="ElectromagneticClassificationOfInspectionSurface"	Name="Electromagnetic Classification of Inspection Surface"
(0014,604C) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="MovingWindowSize"									Name="Moving Window Size"
(0014,604D) VERS="DICONDE"	VR="CS"   VM="1"	Keyword="MovingWindowType"									Name="Moving Window Type"
(0014,604E) VERS="DICONDE"	VR="DS"   VM="1-n"	Keyword="MovingWindowWeights"								Name="Moving Window Weights"
(0014,604F) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="MovingWindowPitch"									Name="Moving Window Pitch"
(0014,6050) VERS="DICONDE"	VR="CS"   VM="1"	Keyword="MovingWindowPaddingScheme"							Name="Moving Window Padding Scheme"
(0014,6051) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="MovingWindowPaddingLength"							Name="Moving Window Padding Sength"
(0014,6052) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="SpatialFilteringParametersSequence"				Name="Spatial Filtering Parameters Sequence"
(0014,6053) VERS="DICONDE"	VR="CS"   VM="1"	Keyword="SpatialFilteringScheme"							Name="Spatial Filtering Scheme"
(0014,6056) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="HorizontalMovingWindowSize"						Name="Horizontal Moving Window Size"
(0014,6057) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="VerticalMovingWindowSize"							Name="Vertical Moving Window Size"
(0014,6059) VERS="DICONDE"	VR="SQ"   VM="1"	Keyword="PolynomialFittingSequence"							Name="Polynomial Fitting Sequence"
(0014,605A) VERS="DICONDE"	VR="CS"   VM="1-n"	Keyword="FittingDataType"									Name="Fitting Data Type"
(0014,605B) VERS="DICONDE"	VR="CS"   VM="1"	Keyword="OperationOnTimeAxisBeforeFitting"					Name="Operation on Time Axis Before Fitting"
(0014,605C) VERS="DICONDE"	VR="CS"   VM="1"	Keyword="OperationOnPixelIntensityBeforeFitting"			Name="Operation on Pixel Intensity Before Fitting"
(0014,605D) VERS="DICONDE"	VR="DS"   VM="1"	Keyword="OrderOfPolynomial"									Name="Order of Polynomial"
(0014,605E) VERS="DICONDE"	VR="CS"   VM="1"	Keyword="IndependentVariableForPolynomialFit"				Name="Independent Variable for Polynomial Fit"
(0014,605F) VERS="DICONDE"	VR="DS"   VM="1-n"	Keyword="PolynomialCoefficients"							Name="PolynomialCoefficients"
(0014,6060) VERS="DICONDE"	VR="CS"   VM="1"	Keyword="ThermographyPixelDataUnit"							Name="Thermography Pixel Data Unit"
